name: build_and_test

on:
  # Run action on certain pull request events
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  # Nightly job on default (main) branch
  schedule:
    - cron: '0 0 * * *'

  # Whenever certain branches are pushed
  push:
    branches: [main]

  # On demand from github.com for testing
  workflow_dispatch:

# Ensures that only one workflow runs at a time for this branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pixi_build_and_test:
    env:
      SCCACHE_DIR: ${{ github.workspace }}/.sccache
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [kilted, jazzy, humble]

    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          # TODO: Remove this either with an org actions runner or public repos.
          token: ${{ secrets.DEPLOY_TOKEN }}
      # Cache build directories and sccache
      - name: Cache build directories and sccache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.SCCACHE_DIR }}
          key: ${{ runner.os }}-build-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build
      - uses: prefix-dev/setup-pixi@v0.8.14
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          frozen: true
          manifest-path: pixi.toml
          # TODO: Remove this when we do not have self-hosted runners in the public repo
          pixi-bin-path: ~/actions-runner/.pixi/bin/pixi
      - name: Build and test
        run: |
          pixi run -e ${{ matrix.ros_distro }} setup-colcon
          pixi run -e ${{ matrix.ros_distro }} build
          pixi run -e ${{ matrix.ros_distro }} test
          pixi run -e ${{ matrix.ros_distro }} test-result
