name: build_and_test

on:
  # Run action on certain pull request events
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  # Nightly job on default (main) branch
  schedule:
    - cron: '0 0 * * *'

  # Whenever certain branches are pushed
  push:
    branches: [main]

  # On demand from github.com for testing
  workflow_dispatch:

# Ensures that only one workflow runs at a time for this branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  pixi_build_and_test:
    timeout-minutes: 15
    env:
      SCCACHE_DIR: ${{ github.workspace }}/.sccache
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [kilted, jazzy, humble]

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      # Cache build directories and sccache
      - name: Cache build directories and sccache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.SCCACHE_DIR }}
          key: ${{ runner.os }}-${{ matrix.ros_distro }}-build-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ros_distro }}-build-${{ github.sha }}
            ${{ runner.os }}-${{ matrix.ros_distro }}-build
      - uses: prefix-dev/setup-pixi@v0.8.14
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          frozen: true
          manifest-path: pixi.toml
      - name: Build and test
        run: |
          pixi run -e ${{ matrix.ros_distro }} setup-colcon
          pixi run -e ${{ matrix.ros_distro }} build
          pixi run -e ${{ matrix.ros_distro }} test
          pixi run -e ${{ matrix.ros_distro }} test-result

  # Build ROS docker images and run tests.
  ros_build_and_test:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [humble, jazzy, kilted, rolling]

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Sanitize tag name
        id: sanitize_tag
        run: |
          BRANCH="${{ github.head_ref || github.ref_name }}"
          TAG="${BRANCH//\//-}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker/Dockerfile
          tags: roboplan_ros_wrapper:${{ github.head_ref || github.ref_name }}
          build-args: |
            ROS_DISTRO=${{ matrix.ros_distro }}
          push: false
          load: true
          cache-from: type=gha,scope=${{ matrix.ros_distro }}
          cache-to: type=gha,mode=max,scope=${{ matrix.ros_distro }}
      - name: Run tests
        run: |
          docker run --rm \
            roboplan_ros_wrapper:${{ github.head_ref || github.ref_name }} \
            bash -c "
              colcon test && \
              colcon test-result --verbose
            "
